version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env.development
    ports:
      - 5432:5432
  api:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env.development
    ports:
      - 3000:3000
volumes:
  db-data:
